dist: focal
sudo: required
services:
- docker
language: go
go:
  - stable
  - tip
env:
  - GO111MODULE=on GOFLAGS=-mod=vendor DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- make test
- bash internal/provider/acceptance.sh
- make vet

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
